###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "user21@example.com",
  "password": "123456"
}

###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "user21@example.com",
  "password": "123456"
}


###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "user21@example.com",
  "password": "123456"
}

###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@admin",
  "password": "admin"
}

###
GET http://localhost:8000/api/v1/protected/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NTAwNTM2NS0zZWIyLTRiODYtODZmMi1hN2Q5MzZjOGYwZDAiLCJlbWFpbCI6InVzZXIyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ0OTY4MDIzfQ.lIvzXlFDgLtVV2auSR9jYYfQ-IWP7nGfFjfDf4ZJA7A

###
GET http://localhost:8000/api/v1/protected/admin-only
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NTAwNTM2NS0zZWIyLTRiODYtODZmMi1hN2Q5MzZjOGYwZDAiLCJlbWFpbCI6InVzZXIyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ0OTY4MDIzfQ.lIvzXlFDgLtVV2auSR9jYYfQ-IWP7nGfFjfDf4ZJA7A
