version: "3.9"
services:
  user-db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - PGPORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-user_service}
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user-service:
    env_file:
      - .env
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${SERVER_PORT} --reload
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - user-db
    environment:
      PYTHONPATH: "/app"
    volumes:
      - .:/app

volumes:
  user_db_data:
