version: "3.9"
services:
  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user-service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - user-db
    environment:
      PYTHONPATH: "/app"
    volumes:
      - .:/app

volumes:
  user_db_data:
