version: "3.9"

services:
  rag-service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${SERVER_PORT} --reload
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: "/app"
    depends_on:
      - redis

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
