version: "3.9"

services:
  rag-service:
    env_file:
      - .env
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${SERVER_PORT} --reload
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: "/app"
    depends_on:
      - rag-db
      - qdrant
      - redis
      - celery-worker

  redis:
    image: redis:7

  celery-worker:
    build: .
    env_file:
      - .env
    command: celery -A app.worker.celery_app worker -E --loglevel=INFO
    depends_on:
      - redis
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    env_file:
      - .env
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
    - PGPORT=${DATABASE_PORT}
    volumes:
      - rag_db_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  rag_db_data:
