apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: llm-rag-app
spec:
  serviceName: "qdrant"
  replicas: 3
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: llm-rag-app
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
  - protocol: TCP
    port: 6333
    targetPort: 6333