apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: llm-rag-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
      - name: rag-service
        image: <registry-url>/rag-service:latest
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: rag-service-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: llm-rag-app
spec:
  type: ClusterIP
  selector:
    app: rag-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001