apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: llm-rag-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: <registry-url>/user-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: user-service-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: llm-rag-app
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000