###
GET http://localhost:8001/api/v1/health

###
POST http://localhost:8001/api/v1/upload/ingest
Content-Type: application/json

{"texts": ["This is a document about RAG", "This one is about embeddings."]}


###
GET http://localhost:8001/api/v1/search?query=quick fox

