POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123",
}

###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
GET http://localhost:8000/api/v1/protected/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ0Mjg5Mjk0fQ.emmonoy15E1xkrQ4tCA822-u8nozX_vP2RuvoC3JvnQ

###
GET http://localhost:8000/api/v1/protected/admin-only
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ0Mjg5Mjk0fQ.emmonoy15E1xkrQ4tCA822-u8nozX_vP2RuvoC3JvnQ
